spring:
  datasource: #띄어쓰기 2칸
    url: jdbc:h2:tcp://localhost/~/forwiz #4칸
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
    #hidden-method 활성화 
    #form 전송시 delete, put 사용 설정
  mvc:
    hidden-method:
      filter:
        enabled: true
        
  jpa: #띄어쓰기 2칸
    hibernate: #띄어쓰기 4칸
      ddl-auto: create #띄어쓰기 6칸
    properties: #띄어쓰기 4칸
      hibernate: #띄어쓰기 6칸
        # show_sql: true #띄어쓰기 8칸
        format_sql: true #띄어쓰기 8칸
   
   #multipart 업로드 max size 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level: #띄어쓰기 없음
    org.hibernate.SQL: debug #띄어쓰기 2칸

  #upload 위치
upload:
  path: C:/multipart/file/